name: Deploy Crack Detection App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to EC2-1
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST1 }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/CrackDetectionWebApp
          git pull origin main
          pkill -f app.py || true
          nohup python3 app.py > output.log 2>&1 &

    - name: Deploy to EC2-2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST2 }}
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/CrackDetectionWebApp
          git pull origin main
          pkill -f app.py || true
          nohup python3 app.py > output.log 2>&1 &